# Generated by Django 2.0.5 on 2018-05-24 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='host name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(null=True)),
                ('introduced_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linkee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('bio', models.TextField()),
                ('welcome_sent_at', models.DateTimeField(null=True)),
                ('last_contacted_at', models.DateTimeField(null=True)),
                ('last_scheduled_at', models.DateTimeField(null=True)),
                ('subscribed_at', models.DateTimeField(null=True)),
                ('unsubscribed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='linkup name')),
                ('welcome_message', models.TextField(blank=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkbaby.Host')),
            ],
        ),
        migrations.AddField(
            model_name='linkee',
            name='linkup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkbaby.Linkup'),
        ),
        migrations.AddField(
            model_name='introduction',
            name='linkup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkbaby.Linkup'),
        ),
        migrations.AddField(
            model_name='introduction',
            name='recipients',
            field=models.ManyToManyField(to='linkbaby.Linkee'),
        ),
    ]
